# Generated by Django 5.1.3 on 2024-11-21 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid email format', regex='^[^@]+@[^@]+\\.[^@]+$')])),
                ('firstname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only Greek characters are allowed', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('lastname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only Greek characters are allowed', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('email__regex', '%@%.%'), models.Q(('email__regex', '%@%.%@%'), _negated=True)), name='chk_email'), models.CheckConstraint(condition=models.Q(('firstname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_firstname'), models.CheckConstraint(condition=models.Q(('lastname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_lastname'), models.CheckConstraint(condition=models.Q(('tel__regex', '^[0-9]+$')), name='chk_tel')],
            },
        ),
    ]
