# Generated by Django 5.1.4 on 2024-12-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='s_id',
            new_name='id',
        ),
    ]
