# Generated by Django 5.1.3 on 2024-11-21 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid password format', regex='^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};\\\':",.<>\\/?]{8,12}$')]),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('password__regex', '^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};\\\':",.<>\\/?]{8,12}$')), name='chk_password'),
        ),
    ]
