# Generated by Django 5.1.3 on 2024-11-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_client_chk_password_remove_staff_s_password_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staff',
            name='chk_s_password',
        ),
    ]
