# Generated by Django 5.1.3 on 2024-11-23 18:37

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_booking_c_id_remove_booking_r_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('m_email', models.CharField(max_length=20, validators=[api.models.email_validator])),
                ('m_firstname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name must contain only Greek letters.', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('m_lastname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name must contain only Greek letters.', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('m_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Telephone number must contain only digits.', regex='^[0-9]+$')])),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Message',
                'constraints': [models.CheckConstraint(condition=models.Q(('m_email__regex', '%@%.%'), models.Q(('m_email__regex', '%@%.%@%'), _negated=True)), name='chk_m_email'), models.CheckConstraint(condition=models.Q(('m_firstname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_m_firstname'), models.CheckConstraint(condition=models.Q(('m_lastname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_m_lastname'), models.CheckConstraint(condition=models.Q(('m_tel__regex', '^[0-9]+$')), name='chk_m_tel')],
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4')])),
                ('availability', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Invalid availability status', regex='^(yes|no)$')])),
                ('r_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'Rooms',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__in', [2, 3, 4])), name='chk_capacity'), models.CheckConstraint(condition=models.Q(('availability__in', ['yes', 'no'])), name='chk_availability')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rooms')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only uppercase English letters and spaces are allowed', regex='^[A-Z ]+$')])),
                ('month_year', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
                ('CVV', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booking')),
            ],
            options={
                'db_table': 'Payment',
                'constraints': [models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9]+$')), name='chk_number'), models.CheckConstraint(condition=models.Q(('name__regex', '^[A-Z ]+$')), name='chk_name'), models.CheckConstraint(condition=models.Q(('month_year__regex', '^[0-9]+$')), name='chk_month_year'), models.CheckConstraint(condition=models.Q(('CVV__regex', '^[0-9]+$')), name='chk_CVV')],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('arrival__lt', models.F('departure'))), name='chk_arrival_before_departure'),
        ),
    ]
