# Generated by Django 5.1.3 on 2024-11-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_staff_chk_s_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='b_id',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='client',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
