# Generated by Django 5.1.3 on 2024-11-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message_rooms_booking_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='c_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='r_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='b_id',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
