# Generated by Django 5.1.3 on 2024-11-21 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_c_id_remove_booking_r_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_email', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid staff email format', regex='^[^@]+@hoteldmd\\.gr$')])),
                ('s_firstname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only Greek characters are allowed', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('s_lastname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Only Greek characters are allowed', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('s_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
                ('salary', models.IntegerField()),
                ('job_descr', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid job description', regex='^(Reception|Administrator|Programmer)$')])),
                ('date_of_joining', models.DateField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('s_email__regex', '%@hoteldmd.gr'), models.Q(('s_email__regex', '%@%.%@%'), _negated=True)), name='chk_s_email'), models.CheckConstraint(condition=models.Q(('s_password__regex', '^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};\\\':",.<>\\/?]{8,12}$')), name='chk_s_password'), models.CheckConstraint(condition=models.Q(('s_firstname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_s_firstname'), models.CheckConstraint(condition=models.Q(('s_lastname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_s_lastname'), models.CheckConstraint(condition=models.Q(('s_tel__regex', '^[0-9]+$')), name='chk_s_tel'), models.CheckConstraint(condition=models.Q(('job_descr__in', ['Reception', 'Administrator', 'Programmer'])), name='chk_job_descr')],
            },
        ),
    ]
