# Generated by Django 5.1.3 on 2024-11-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_client_is_staff_client_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='chk_firstname',
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
