# Generated by Django 5.1.3 on 2024-11-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_staff'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staff',
            name='chk_s_password',
        ),
    ]
