# Generated by Django 5.1.3 on 2024-11-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_client_chk_firstname_alter_client_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='chk_password',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('firstname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_firstname'),
        ),
    ]
