# Generated by Django 5.1.3 on 2024-11-21 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_staff_chk_s_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='s_password',
            field=models.CharField(default=9999, max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid password format', regex='^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};\\\':",.<>\\/?]{8,12}$')]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(condition=models.Q(('s_password__regex', '^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};\\\':",.<>\\/?]{8,12}$')), name='chk_s_password'),
        ),
    ]
