# Generated by Django 5.1.3 on 2024-11-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
