# Generated by Django 5.1.3 on 2024-11-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_staff_s_password_staff_chk_s_password'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staff',
            name='chk_s_password',
        ),
    ]
