# Generated by Django 5.1.3 on 2024-11-21 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_client_chk_password_client_chk_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid email format', regex='^[a-zA-Z0-9]*@[a-zA-Z]*\\.[a-z]*$')]),
        ),
    ]
