# Generated by Django 5.1.3 on 2024-11-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_staff_chk_s_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
