# Generated by Django 5.1.3 on 2024-11-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_client_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='chk_email',
        ),
    ]
