# Generated by Django 5.1.3 on 2024-11-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='CustomUser',
        ),
    ]
