# Generated by Django 5.1.3 on 2024-11-21 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_client_chk_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid email format', regex='^[a-zA-Z0-9]*@[a-zA-Z]*\\.[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Invalid password format', regex='^[a-zA-Z0-9!@#$%^&*()_+\\-=\\[\\]{};\\\':",.<>\\/?]{8,12}$')]),
        ),
    ]
