# Generated by Django 5.1.3 on 2024-11-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_customuser_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
