# Generated by Django 5.1.3 on 2024-11-21 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_client_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_superuser',
        ),
    ]
