# Generated by Django 5.1.3 on 2024-11-28 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_client_date_joined_remove_client_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('m_email', models.CharField(max_length=30)),
                ('m_firstname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name must contain only Greek letters.', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('m_lastname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Name must contain only Greek letters.', regex='^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')])),
                ('m_tel', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Telephone number must contain only digits.', regex='^[0-9]+$')])),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default='defaultus', max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.CheckConstraint(condition=models.Q(('username__regex', '^[a-zA-Z0-9)]{3,20}$')), name='chk_username'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('m_email__regex', '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')), name='chk_m_email'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('m_firstname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_m_firstname'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('m_lastname__regex', '^[Α-ΩΆΈΉΊΌΎΏα-ωάέήίόύώ]*$')), name='chk_m_lastname'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('m_tel__regex', '^[0-9]+$')), name='chk_m_tel'),
        ),
    ]
