# Generated by Django 5.1.3 on 2024-11-28 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_message_client_username_client_chk_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('r_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4')])),
                ('availability', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Invalid availability status', regex='^(yes|no)$')])),
                ('r_cost', models.IntegerField()),
            ],
            options={
                'db_table': 'Room',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__in', [2, 3, 4])), name='chk_capacity'), models.CheckConstraint(condition=models.Q(('availability__in', ['yes', 'no'])), name='chk_availability')],
            },
        ),
    ]
