# Generated by Django 5.1.3 on 2024-11-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='c_id',
            new_name='id',
        ),
    ]
