# Generated by Django 5.1.3 on 2024-12-03 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_c_id_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival', models.DateField()),
                ('departure', models.DateField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'db_table': 'Booking',
                'constraints': [models.CheckConstraint(condition=models.Q(('arrival__lt', models.F('departure'))), name='chk_arrival_before_departure')],
            },
        ),
    ]
