# Generated by Django 5.1.3 on 2024-12-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='r_id',
            new_name='room',
        ),
    ]
