# Generated by Django 5.1.3 on 2024-12-04 10:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_id_booking_client_rename_r_id_booking_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Only uppercase English letters and spaces are allowed', regex='^[A-Z ]+$')])),
                ('month_year', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
                ('CVV', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Only numeric characters are allowed', regex='^[0-9]+$')])),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms_needed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('rooms_needed__in', [1, 2, 3])), name='chk_rooms_needed'),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.booking'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9]+$')), name='chk_number'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('name__regex', '^[A-Z ]+$')), name='chk_name'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('month_year__regex', '^[0-9]+$')), name='chk_month_year'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('CVV__regex', '^[0-9]+$')), name='chk_CVV'),
        ),
    ]
