# Generated by Django 5.1.3 on 2024-12-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_payment_booking_rooms_needed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.AddField(
            model_name='payment',
            name='bookings',
            field=models.ManyToManyField(to='api.booking'),
        ),
    ]
